// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WALLEve.Data;

#nullable disable

namespace WALLEve.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20251229151255_AddMarketAnalysisTables")]
    partial class AddMarketAnalysisTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("WALLEve.Models.Database.MarketHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Average")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Highest")
                        .HasColumnType("REAL");

                    b.Property<double>("Lowest")
                        .HasColumnType("REAL");

                    b.Property<long>("OrderCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeId", "Date");

                    b.HasIndex("RegionId", "TypeId", "Date")
                        .IsUnique();

                    b.ToTable("MarketHistory");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BestBuyPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("BestSellPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("BuyVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellVolume")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Spread")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("RegionId", "TypeId", "Timestamp");

                    b.ToTable("MarketSnapshots");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AIModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PredictedChange")
                        .HasColumnType("REAL");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Strength")
                        .HasColumnType("REAL");

                    b.Property<string>("TimeWindow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "TypeId");

                    b.HasIndex("TrendType", "Strength");

                    b.HasIndex("TypeId", "AnalyzedAt");

                    b.ToTable("MarketTrends");
                });

            modelBuilder.Entity("WALLEve.Models.Database.TradingOpportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AIModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("ActualProfit")
                        .HasColumnType("REAL");

                    b.Property<double?>("BuyPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("BuyRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuySystemId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedProfit")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JumpDistance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpportunityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RequiredCapital")
                        .HasColumnType("REAL");

                    b.Property<string>("RouteSecurityAnalysis")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SellPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("SellRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SellSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuyRegionId");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("SellRegionId");

                    b.HasIndex("Status", "Confidence");

                    b.HasIndex("Status", "ExpiresAt");

                    b.HasIndex("TypeId", "Status");

                    b.ToTable("TradingOpportunities");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCharacter", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.HasIndex("CharacterName");

                    b.HasIndex("LastSyncedAt");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCorporation", b =>
                {
                    b.Property<int>("CorporationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorporationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CorporationId");

                    b.HasIndex("CorporationName");

                    b.HasIndex("LastSyncedAt");

                    b.ToTable("Corporations");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletEntryLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CorporationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Division")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyRejected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyVerified")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TargetEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Confidence");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsManuallyRejected");

                    b.HasIndex("IsManuallyVerified");

                    b.HasIndex("Type");

                    b.HasIndex("CharacterId", "SourceEntryId");

                    b.HasIndex("CharacterId", "TargetEntryId");

                    b.HasIndex("SourceEntryId", "TargetEntryId")
                        .IsUnique();

                    b.HasIndex("CorporationId", "Division", "SourceEntryId");

                    b.HasIndex("CorporationId", "Division", "TargetEntryId");

                    b.ToTable("Links", null, t =>
                        {
                            t.HasCheckConstraint("CK_WalletEntryLink_CharacterOrCorp", "(CharacterId IS NOT NULL AND CorporationId IS NULL) OR (CharacterId IS NULL AND CorporationId IS NOT NULL)");

                            t.HasCheckConstraint("CK_WalletEntryLink_DivisionForCorpOnly", "(CorporationId IS NOT NULL AND Division BETWEEN 1 AND 7) OR (CorporationId IS NULL AND Division IS NULL)");
                        });
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletEntryLink", b =>
                {
                    b.HasOne("WALLEve.Models.Database.WalletCharacter", "Character")
                        .WithMany("Links")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WALLEve.Models.Database.WalletCorporation", "Corporation")
                        .WithMany("Links")
                        .HasForeignKey("CorporationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Character");

                    b.Navigation("Corporation");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCharacter", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCorporation", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
