// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WALLEve.Data;

#nullable disable

namespace WALLEve.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20260913114217_AddMarketHubProfiles")]
    partial class AddMarketHubProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("WALLEve.Models.Database.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("WALLEve.Models.Database.BackgroundJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Current")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("JobType", "Status");

                    b.ToTable("BackgroundJobs");
                });

            modelBuilder.Entity("WALLEve.Models.Database.CostBasisEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstimateRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Source");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("CharacterId", "TypeId")
                        .IsUnique();

                    b.ToTable("CostBasisEntries");
                });

            modelBuilder.Entity("WALLEve.Models.Database.CostBasisLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("CharacterId", "TypeId", "Date");

                    b.HasIndex("CharacterId", "TypeId", "SourceTransactionId")
                        .IsUnique();

                    b.ToTable("CostBasisLedgerEntries");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketFavorit", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "TypeId");

                    b.HasIndex("CharacterId");

                    b.ToTable("MarketFavorits");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Average")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Highest")
                        .HasColumnType("REAL");

                    b.Property<double>("Lowest")
                        .HasColumnType("REAL");

                    b.Property<long>("OrderCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeId", "Date");

                    b.HasIndex("RegionId", "TypeId", "Date")
                        .IsUnique();

                    b.ToTable("MarketHistory");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketHubProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActiveHub")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComparisonMarket")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActiveHub");

                    b.HasIndex("IsComparisonMarket");

                    b.HasIndex("SystemId")
                        .IsUnique();

                    b.ToTable("MarketHubProfiles");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BestBuyLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BestBuyPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("BestBuySystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BestSellLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BestSellPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("BestSellSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BuyVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SellVolume")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Spread")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("RegionId", "TypeId", "Timestamp");

                    b.ToTable("MarketSnapshots");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AIModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PredictedChange")
                        .HasColumnType("REAL");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Strength")
                        .HasColumnType("REAL");

                    b.Property<string>("TimeWindow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "TypeId");

                    b.HasIndex("TrendType", "Strength");

                    b.HasIndex("TypeId", "AnalyzedAt");

                    b.ToTable("MarketTrends");
                });

            modelBuilder.Entity("WALLEve.Models.Database.TradingOpportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualProfit")
                        .HasColumnType("REAL");

                    b.Property<string>("AlgorithmVersion")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BuyLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BuyPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("BuyRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuySystemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataQuality")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedProfit")
                        .HasColumnType("REAL");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JumpDistance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpportunityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RequiredCapital")
                        .HasColumnType("REAL");

                    b.Property<string>("RouteSecurityAnalysis")
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<long?>("SellLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SellPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("SellRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SellSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuyRegionId");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("SellRegionId");

                    b.HasIndex("Status", "ExpiresAt");

                    b.HasIndex("Status", "Score");

                    b.HasIndex("TypeId", "Status");

                    b.HasIndex("CharacterId", "Status", "OpportunityType");

                    b.ToTable("TradingOpportunities");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCharacter", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.HasIndex("CharacterName");

                    b.HasIndex("LastSyncedAt");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCorporation", b =>
                {
                    b.Property<int>("CorporationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorporationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CorporationId");

                    b.HasIndex("CorporationName");

                    b.HasIndex("LastSyncedAt");

                    b.ToTable("Corporations");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletEntryLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CorporationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Division")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyRejected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyVerified")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TargetEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Confidence");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsManuallyRejected");

                    b.HasIndex("IsManuallyVerified");

                    b.HasIndex("Type");

                    b.HasIndex("CharacterId", "SourceEntryId");

                    b.HasIndex("CharacterId", "TargetEntryId");

                    b.HasIndex("SourceEntryId", "TargetEntryId")
                        .IsUnique();

                    b.HasIndex("CorporationId", "Division", "SourceEntryId");

                    b.HasIndex("CorporationId", "Division", "TargetEntryId");

                    b.ToTable("Links", null, t =>
                        {
                            t.HasCheckConstraint("CK_WalletEntryLink_CharacterOrCorp", "(CharacterId IS NOT NULL AND CorporationId IS NULL) OR (CharacterId IS NULL AND CorporationId IS NOT NULL)");

                            t.HasCheckConstraint("CK_WalletEntryLink_DivisionForCorpOnly", "(CorporationId IS NOT NULL AND Division BETWEEN 1 AND 7) OR (CorporationId IS NULL AND Division IS NULL)");
                        });
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletTransactionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("JournalRefId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("CharacterId", "TransactionId")
                        .IsUnique();

                    b.HasIndex("CharacterId", "TypeId", "IsBuy");

                    b.ToTable("WalletTransactionRecords");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationFlag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "TypeId");

                    b.HasIndex("TypeId", "IsSingleton");

                    b.ToTable("HoldingItems");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SyncRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SyncRunId");

                    b.HasIndex("OwnerType", "OwnerId", "SyncedAt");

                    b.ToTable("HoldingSnapshots");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingSyncRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId", "StartedAt");

                    b.ToTable("HoldingSyncRuns");
                });

            modelBuilder.Entity("WALLEve.Models.Portfolio.PortfolioSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CostBasisKnownItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HoldingSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnknownCostBasisItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnknownValuationItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValuedItemCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HoldingSnapshotId")
                        .IsUnique();

                    b.HasIndex("OwnerType", "OwnerId", "CapturedAt");

                    b.ToTable("PortfolioSnapshots");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketFavorit", b =>
                {
                    b.HasOne("WALLEve.Models.Database.WalletCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletEntryLink", b =>
                {
                    b.HasOne("WALLEve.Models.Database.WalletCharacter", "Character")
                        .WithMany("Links")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WALLEve.Models.Database.WalletCorporation", "Corporation")
                        .WithMany("Links")
                        .HasForeignKey("CorporationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Character");

                    b.Navigation("Corporation");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingItem", b =>
                {
                    b.HasOne("WALLEve.Models.Holdings.HoldingSnapshot", "Snapshot")
                        .WithMany("Items")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingSnapshot", b =>
                {
                    b.HasOne("WALLEve.Models.Holdings.HoldingSyncRun", "SyncRun")
                        .WithMany("Snapshots")
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncRun");
                });

            modelBuilder.Entity("WALLEve.Models.Portfolio.PortfolioSnapshot", b =>
                {
                    b.HasOne("WALLEve.Models.Holdings.HoldingSnapshot", "SourceSnapshot")
                        .WithMany()
                        .HasForeignKey("HoldingSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceSnapshot");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCharacter", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCorporation", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingSnapshot", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingSyncRun", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
