// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WALLEve.Data;

#nullable disable

namespace WALLEve.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20260917111216_AddIndustryJobEntries")]
    partial class AddIndustryJobEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("WALLEve.Models.Database.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("WALLEve.Models.Database.BackgroundJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Current")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("JobType", "Status");

                    b.ToTable("BackgroundJobs");
                });

            modelBuilder.Entity("WALLEve.Models.Database.CostBasisEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstimateRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Source");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("CharacterId", "TypeId")
                        .IsUnique();

                    b.ToTable("CostBasisEntries");
                });

            modelBuilder.Entity("WALLEve.Models.Database.CostBasisLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("CharacterId", "TypeId", "Date");

                    b.HasIndex("CharacterId", "TypeId", "SourceTransactionId")
                        .IsUnique();

                    b.ToTable("CostBasisLedgerEntries");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketFavorit", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "TypeId");

                    b.HasIndex("CharacterId");

                    b.ToTable("MarketFavorits");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Average")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Highest")
                        .HasColumnType("REAL");

                    b.Property<double>("Lowest")
                        .HasColumnType("REAL");

                    b.Property<long>("OrderCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeId", "Date");

                    b.HasIndex("RegionId", "TypeId", "Date")
                        .IsUnique();

                    b.ToTable("MarketHistory");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketHubProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActiveHub")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComparisonMarket")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActiveHub");

                    b.HasIndex("IsComparisonMarket");

                    b.HasIndex("SystemId")
                        .IsUnique();

                    b.ToTable("MarketHubProfiles");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BestBuyLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BestBuyPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("BestBuySystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BestSellLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BestSellPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("BestSellSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BuyVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SellVolume")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Spread")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("RegionId", "TypeId", "Timestamp");

                    b.ToTable("MarketSnapshots");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AIModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PredictedChange")
                        .HasColumnType("REAL");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Strength")
                        .HasColumnType("REAL");

                    b.Property<string>("TimeWindow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "TypeId");

                    b.HasIndex("TrendType", "Strength");

                    b.HasIndex("TypeId", "AnalyzedAt");

                    b.ToTable("MarketTrends");
                });

            modelBuilder.Entity("WALLEve.Models.Database.TradingOpportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualProfit")
                        .HasColumnType("REAL");

                    b.Property<string>("AlgorithmVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerFeeOrigin")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BrokerFeeRate")
                        .HasColumnType("REAL");

                    b.Property<long?>("BuyLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BuyPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("BuyRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuySystemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataQuality")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedProfit")
                        .HasColumnType("REAL");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FeeEvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JumpDistance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpportunityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RequiredCapital")
                        .HasColumnType("REAL");

                    b.Property<string>("RouteSecurityAnalysis")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalesTaxOrigin")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SalesTaxRate")
                        .HasColumnType("REAL");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<long?>("SellLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SellPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("SellRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SellSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandingsOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuyRegionId");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("SellRegionId");

                    b.HasIndex("Status", "ExpiresAt");

                    b.HasIndex("Status", "Score");

                    b.HasIndex("TypeId", "Status");

                    b.HasIndex("CharacterId", "Status", "OpportunityType");

                    b.ToTable("TradingOpportunities");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCharacter", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.HasIndex("CharacterName");

                    b.HasIndex("LastSyncedAt");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCorporation", b =>
                {
                    b.Property<int>("CorporationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorporationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CorporationId");

                    b.HasIndex("CorporationName");

                    b.HasIndex("LastSyncedAt");

                    b.ToTable("Corporations");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletEntryLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CorporationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Division")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyRejected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyVerified")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TargetEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Confidence");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsManuallyRejected");

                    b.HasIndex("IsManuallyVerified");

                    b.HasIndex("Type");

                    b.HasIndex("CharacterId", "SourceEntryId");

                    b.HasIndex("CharacterId", "TargetEntryId");

                    b.HasIndex("SourceEntryId", "TargetEntryId")
                        .IsUnique();

                    b.HasIndex("CorporationId", "Division", "SourceEntryId");

                    b.HasIndex("CorporationId", "Division", "TargetEntryId");

                    b.ToTable("Links", null, t =>
                        {
                            t.HasCheckConstraint("CK_WalletEntryLink_CharacterOrCorp", "(CharacterId IS NOT NULL AND CorporationId IS NULL) OR (CharacterId IS NULL AND CorporationId IS NOT NULL)");

                            t.HasCheckConstraint("CK_WalletEntryLink_DivisionForCorpOnly", "(CorporationId IS NOT NULL AND Division BETWEEN 1 AND 7) OR (CorporationId IS NULL AND Division IS NULL)");
                        });
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletTransactionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("JournalRefId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("CharacterId", "TransactionId")
                        .IsUnique();

                    b.HasIndex("CharacterId", "TypeId", "IsBuy");

                    b.ToTable("WalletTransactionRecords");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationFlag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "TypeId");

                    b.HasIndex("TypeId", "IsSingleton");

                    b.ToTable("HoldingItems");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SyncRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SyncRunId");

                    b.HasIndex("OwnerType", "OwnerId", "SyncedAt");

                    b.ToTable("HoldingSnapshots");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingSyncRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId", "StartedAt");

                    b.ToTable("HoldingSyncRuns");
                });

            modelBuilder.Entity("WALLEve.Models.Industry.IndustryJobEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlueprintId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlueprintLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlueprintTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Cost")
                        .HasColumnType("REAL");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstallerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LicensedRuns")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OutputLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PauseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SuccessfulRuns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "EndDate");

                    b.HasIndex("CharacterId", "JobId")
                        .IsUnique();

                    b.HasIndex("CharacterId", "Status");

                    b.ToTable("IndustryJobEntries");
                });

            modelBuilder.Entity("WALLEve.Models.Mining.MiningLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SolarSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Date");

                    b.HasIndex("CharacterId", "Date", "TypeId", "SolarSystemId")
                        .IsUnique();

                    b.ToTable("MiningLedgerEntries");
                });

            modelBuilder.Entity("WALLEve.Models.Portfolio.PortfolioHistoryCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EscrowItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EscrowQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EscrowValue")
                        .HasColumnType("REAL");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PointId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.ToTable("PortfolioHistoryCategories");
                });

            modelBuilder.Entity("WALLEve.Models.Portfolio.PortfolioHistoryLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EscrowItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EscrowQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EscrowValue")
                        .HasColumnType("REAL");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationFlag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PointId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.ToTable("PortfolioHistoryLocations");
                });

            modelBuilder.Entity("WALLEve.Models.Portfolio.PortfolioHistoryPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetsItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AssetsQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AssetsValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CostBasisKnownItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EscrowItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EscrowQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EscrowValue")
                        .HasColumnType("REAL");

                    b.Property<long>("HoldingSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("KnownBasisValue")
                        .HasColumnType("REAL");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RealizedProfit")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("UnknownBasisMarketValue")
                        .HasColumnType("REAL");

                    b.Property<long>("UnknownBasisQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnknownCostBasisItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnknownValuationItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnknownValuationQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnknownValuationTypeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValuatedTypeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValuationHubName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ValuationRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WalletCashInflow")
                        .HasColumnType("REAL");

                    b.Property<double?>("WalletCashOutflow")
                        .HasColumnType("REAL");

                    b.Property<int>("WalletTransactionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HoldingSnapshotId")
                        .IsUnique();

                    b.HasIndex("OwnerType", "OwnerId", "CapturedAt");

                    b.ToTable("PortfolioHistoryPoints");
                });

            modelBuilder.Entity("WALLEve.Models.Portfolio.PortfolioSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CostBasisKnownItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HoldingSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnknownCostBasisItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnknownValuationItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValuedItemCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HoldingSnapshotId")
                        .IsUnique();

                    b.HasIndex("OwnerType", "OwnerId", "CapturedAt");

                    b.ToTable("PortfolioSnapshots");
                });

            modelBuilder.Entity("WALLEve.Models.Stockpiles.StockpileTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TypeId");

                    b.HasIndex("OwnerType", "OwnerId", "IsArchived");

                    b.HasIndex("OwnerType", "OwnerId", "TypeId")
                        .IsUnique()
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("StockpileTargets");
                });

            modelBuilder.Entity("WALLEve.Models.Trading.ActualNetCorrection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttributionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CorrectedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NewActualNet")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousActualNet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingOpportunityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttributionId", "CorrectedAt");

                    b.HasIndex("CharacterId", "CorrectedAt");

                    b.ToTable("ActualNetCorrections");
                });

            modelBuilder.Entity("WALLEve.Models.Trading.AttributionTransactionLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttributionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingOpportunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AttributionId", "TransactionId")
                        .IsUnique();

                    b.HasIndex("CharacterId", "TransactionId");

                    b.HasIndex("TradingOpportunityId", "TransactionDate");

                    b.ToTable("AttributionTransactionLinks");
                });

            modelBuilder.Entity("WALLEve.Models.Trading.RecommendationAttribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ActualNet")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttributedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedNetMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedNetMin")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeeKnowledge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingOpportunityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "MatchState");

                    b.HasIndex("TradingOpportunityId", "CharacterId")
                        .IsUnique();

                    b.HasIndex("TypeId", "Side", "WindowStartUtc");

                    b.ToTable("RecommendationAttributions");
                });

            modelBuilder.Entity("WALLEve.Models.Trading.TradeContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BreakEvenPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BrokerFee")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BrokerRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BuyLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuyMarketSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BuyPricePerUnit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BuyRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CostBasisSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentPricePerUnit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EstimatedExtraNetProceeds")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedNetProceeds")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedProfit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActionable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JumpCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JumpDistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MarketSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ModifyFee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetRoiPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotActionableReason")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RelistDiscountPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RequiredCapital")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalesTax")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalesTaxPercent")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SellLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SellLocationLabel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SellMarketSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SellPricePerUnit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SellRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SuggestedPricePerUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingOpportunityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UnitCostBasis")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuyMarketSnapshotId");

                    b.HasIndex("MarketSnapshotId");

                    b.HasIndex("SellMarketSnapshotId");

                    b.HasIndex("TradingOpportunityId", "Kind");

                    b.HasIndex("CharacterId", "Kind", "CreatedAt");

                    b.ToTable("TradeContracts");
                });

            modelBuilder.Entity("WALLEve.Models.Trading.TradeProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowHighSec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowLowSec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowNullSec")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastReportedFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxCapital")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxCargoVolume")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxJumps")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MinProfit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinQualityScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MinVolumeM3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SignalDeactivated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("CharacterId", "UpdatedAt");

                    b.ToTable("TradeProfiles");
                });

            modelBuilder.Entity("WALLEve.Models.Trading.TradeStatusChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingOpportunityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "ChangedAt");

                    b.HasIndex("ToStatus", "Source");

                    b.HasIndex("TradingOpportunityId", "ChangedAt");

                    b.ToTable("TradeStatusChanges");
                });

            modelBuilder.Entity("WALLEve.Models.Database.MarketFavorit", b =>
                {
                    b.HasOne("WALLEve.Models.Database.WalletCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletEntryLink", b =>
                {
                    b.HasOne("WALLEve.Models.Database.WalletCharacter", "Character")
                        .WithMany("Links")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WALLEve.Models.Database.WalletCorporation", "Corporation")
                        .WithMany("Links")
                        .HasForeignKey("CorporationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Character");

                    b.Navigation("Corporation");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingItem", b =>
                {
                    b.HasOne("WALLEve.Models.Holdings.HoldingSnapshot", "Snapshot")
                        .WithMany("Items")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingSnapshot", b =>
                {
                    b.HasOne("WALLEve.Models.Holdings.HoldingSyncRun", "SyncRun")
                        .WithMany("Snapshots")
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncRun");
                });

            modelBuilder.Entity("WALLEve.Models.Portfolio.PortfolioHistoryCategory", b =>
                {
                    b.HasOne("WALLEve.Models.Portfolio.PortfolioHistoryPoint", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("WALLEve.Models.Portfolio.PortfolioHistoryLocation", b =>
                {
                    b.HasOne("WALLEve.Models.Portfolio.PortfolioHistoryPoint", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("WALLEve.Models.Portfolio.PortfolioHistoryPoint", b =>
                {
                    b.HasOne("WALLEve.Models.Holdings.HoldingSnapshot", "SourceSnapshot")
                        .WithMany()
                        .HasForeignKey("HoldingSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceSnapshot");
                });

            modelBuilder.Entity("WALLEve.Models.Portfolio.PortfolioSnapshot", b =>
                {
                    b.HasOne("WALLEve.Models.Holdings.HoldingSnapshot", "SourceSnapshot")
                        .WithMany()
                        .HasForeignKey("HoldingSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceSnapshot");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCharacter", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCorporation", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingSnapshot", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WALLEve.Models.Holdings.HoldingSyncRun", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
