// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WALLEve.Data;

#nullable disable

namespace WALLEve.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    partial class WalletDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("WALLEve.Models.Database.WalletCharacter", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.HasIndex("CharacterName");

                    b.HasIndex("LastSyncedAt");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCorporation", b =>
                {
                    b.Property<int>("CorporationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorporationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CorporationId");

                    b.HasIndex("CorporationName");

                    b.HasIndex("LastSyncedAt");

                    b.ToTable("Corporations");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletEntryLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CorporationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Division")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyRejected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyVerified")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TargetEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Confidence");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsManuallyRejected");

                    b.HasIndex("IsManuallyVerified");

                    b.HasIndex("Type");

                    b.HasIndex("CharacterId", "SourceEntryId");

                    b.HasIndex("CharacterId", "TargetEntryId");

                    b.HasIndex("SourceEntryId", "TargetEntryId")
                        .IsUnique();

                    b.HasIndex("CorporationId", "Division", "SourceEntryId");

                    b.HasIndex("CorporationId", "Division", "TargetEntryId");

                    b.ToTable("Links", t =>
                        {
                            t.HasCheckConstraint("CK_WalletEntryLink_CharacterOrCorp", "(CharacterId IS NOT NULL AND CorporationId IS NULL) OR (CharacterId IS NULL AND CorporationId IS NOT NULL)");

                            t.HasCheckConstraint("CK_WalletEntryLink_DivisionForCorpOnly", "(CorporationId IS NOT NULL AND Division BETWEEN 1 AND 7) OR (CorporationId IS NULL AND Division IS NULL)");
                        });
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletEntryLink", b =>
                {
                    b.HasOne("WALLEve.Models.Database.WalletCharacter", "Character")
                        .WithMany("Links")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WALLEve.Models.Database.WalletCorporation", "Corporation")
                        .WithMany("Links")
                        .HasForeignKey("CorporationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Character");

                    b.Navigation("Corporation");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCharacter", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("WALLEve.Models.Database.WalletCorporation", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
